# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(611, 547)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.aeTab = QtWidgets.QWidget()
        self.aeTab.setObjectName("aeTab")
        self.gridLayout = QtWidgets.QGridLayout(self.aeTab)
        self.gridLayout.setObjectName("gridLayout")
        self.listWidget = QtWidgets.QListWidget(self.aeTab)
        self.listWidget.setIconSize(QtCore.QSize(32, 32))
        self.listWidget.setViewMode(QtWidgets.QListView.IconMode)
        self.listWidget.setObjectName("listWidget")
        self.gridLayout.addWidget(self.listWidget, 2, 0, 1, 3)
        self.newAutoEncoderNameLineEdit = QtWidgets.QLineEdit(self.aeTab)
        self.newAutoEncoderNameLineEdit.setObjectName("newAutoEncoderNameLineEdit")
        self.gridLayout.addWidget(self.newAutoEncoderNameLineEdit, 0, 1, 1, 1)
        self.newAutoEncoderSaveButton = QtWidgets.QPushButton(self.aeTab)
        self.newAutoEncoderSaveButton.setObjectName("newAutoEncoderSaveButton")
        self.gridLayout.addWidget(self.newAutoEncoderSaveButton, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.aeTab)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.addImagesButton = QtWidgets.QPushButton(self.aeTab)
        self.addImagesButton.setObjectName("addImagesButton")
        self.horizontalLayout.addWidget(self.addImagesButton)
        self.clearImageListButton = QtWidgets.QPushButton(self.aeTab)
        self.clearImageListButton.setObjectName("clearImageListButton")
        self.horizontalLayout.addWidget(self.clearImageListButton)
        self.saveImageListButton = QtWidgets.QPushButton(self.aeTab)
        self.saveImageListButton.setObjectName("saveImageListButton")
        self.horizontalLayout.addWidget(self.saveImageListButton)
        self.openImageListButton = QtWidgets.QPushButton(self.aeTab)
        self.openImageListButton.setObjectName("openImageListButton")
        self.horizontalLayout.addWidget(self.openImageListButton)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 3)
        self.trainAutoEncoderButton = QtWidgets.QPushButton(self.aeTab)
        self.trainAutoEncoderButton.setObjectName("trainAutoEncoderButton")
        self.gridLayout.addWidget(self.trainAutoEncoderButton, 3, 0, 1, 1)
        self.tabWidget.addTab(self.aeTab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 611, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Neural network UI"))
        self.newAutoEncoderSaveButton.setText(_translate("MainWindow", "..."))
        self.label.setText(_translate("MainWindow", "Nom du fichier de destination"))
        self.addImagesButton.setText(_translate("MainWindow", "Ajouter des images"))
        self.clearImageListButton.setText(_translate("MainWindow", "Effacer la liste"))
        self.saveImageListButton.setText(_translate("MainWindow", "Enregistrer cette liste d\'images"))
        self.openImageListButton.setText(_translate("MainWindow", "Ouvrir une liste d\'images"))
        self.trainAutoEncoderButton.setText(_translate("MainWindow", "Entraîner l\'autoencodeur"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.aeTab), _translate("MainWindow", "Entraîner un nouvel auto-encodeur"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
